services:
  backend:
    build:
      context: .
    env_file: ".env"
    image: nexus-iq/backend
    ports:
      - 8000:8000

  database:
    image: postgres:18-alpine
    environment:
      POSTGRES_PASSWORD: geheim2
      POSTGRES_DB: nexus_iq
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
